# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c52dfc9d3175ffd592100f6adbef8e04596629bff2834b5b1d1337916c60ad94f40b8534f8ec42929b9e8830317ee07fbcaf396eaa574dad8137b436f10c257a

test:
  secret_key_base: 4b210f9710764efcf9a6221324db31fc3d176728376fd969e31436a6ed5ef543766b3f0904da460a07cba6641e22dc638ce97b0db4fd673b88453c385168fb7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
